[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "font",
]

[profile.release]
lto = true
debug = 1
incremental = false

[patch.crates-io]
freetype = { git = "https://github.com/servo/rust-freetype.git" }
